SELECT MEMBER_ID
    , MEMBER_NAME
    , GENDER
    , TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W'
AND SUBSTR(TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD'), 6, 2) = '03'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;