SELECT BOOK_ID
     --, SUBSTR(PUBLISHED_DATE, 8)
     , TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
  FROM BOOK
WHERE 1=1
  AND CATEGORY = '인문'
  AND TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') LIKE '2021%'
ORDER BY PUBLISHED_DATE ASC;